# Jykell configuration
date_format: "%b %-d, %Y"
paginate: 5
language: 'zh-cn'
encoding: "utf-8"

# You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages.
# Your site will use 'rouge' for highlighting instead.
# To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information,
# see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.
# highlighter: pygments
highlighter: rouge

# You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st.
# At that time, your site will use 'kramdown' for markdown rendering instead.
# To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected.
# For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.
# markdown: redcarpet # [ maruku | rdiscount | kramdown | redcarpet ]
# redcarpet:
#     extensions:
        # - fenced_code_blocks
        # - no_intra_emphasis
        # - strikethrough
        # - space_after_headers
        # - autolink
        # - hard_wrap
        # - tables
        # - superscript
        # - highlight
        # - prettify
        # - with_toc_data

markdown:    kramdown
lsi:         false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style


# Website info
name: 'Valar morghulis'
description: "The night is dark and full of terrors."

# Author's info
author: 'Moch Xiao'
# edit 'categories' in the front matter of every post to match this username
nickname: moch
bio: 'iOS Develpoer'
location: 'Chengdu, CN'
url: 'https://github.com/cuzv'
short_url: 'cuzv'
image: 'assets/images/avatar.png'

disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: cuzv
repo: blog
branch: master
relative_source: ./
destination: ./_site
production_url:  http://mochxiao.com
source_url:      https://github.com/cuzv/blog/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

# Google Analytics
ga:
  id:
  host:
